# Generated by Django 2.2.5 on 2019-12-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('men', 'Man'), ('women', 'Woman'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
